
serenity {
  project.name = "Serenity Screenplay Framework"
  take.screenshots = FOR_FAILURES
  restart.browser.for.each = SCENARIO
  threads = 2
}

webdriver {
  driver = chrome
  timeouts {
    implicitly wait = 5000
  }
  capabilities {
    "goog:chromeOptions" {
      args = ["--start-maximized", "--disable-notifications"]
    }
  }
}
